### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [npes87184/S2TDroid#14]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you? Since F-Droid builds everything from source, we would have to remove [this jar](https://github.com/npes87184/S2TDroid/blob/pro/app/libs/juniversalchardet-1.0.3.jar).

**Comment by npes87184** [comment]
Hi,

I am ok to publish this app to F-Droid. However, I am not familiar with F-Droid.
Would I need to upload new version to F-Droid each time when I release new version of this app?

Thanks.

**Comment by linsui** [comment]
We pick new versions automatic. You just need to bump the version code and tag a new release.

**Comment by linsui** [comment]
I opened an MR in fdroiddata. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10481

**Comment by npes87184** [comment]
I have merged fastlane PR, thank you.

**Comment by linsui** [comment]
The fdroiddata MR is merged. The app will be published in 2-3 days. This is the F-Droid‘s badge. Thanks!

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.npes87184.s2tdroid.donate)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.npes87184.s2tdroid.donate)
```
